export interface PdfReportData {
  title: string;
  date: string;
  originalImageUrl: string;
  depthMapUrl?: string;
  viewer3DUrl?: string;
  notes?: string;
  disclaimer: string;
}

export async function generatePdfReport(data: PdfReportData): Promise<Blob> {
  // For now, create a simple HTML-based "PDF" that can be printed
  // In production, you'd use a library like jspdf or pdf-lib
  
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${data.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      color: #111827;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #2563EB;
    }
    .header h1 {
      color: #2563EB;
      margin: 0 0 10px 0;
    }
    .header p {
      color: #6B7280;
      margin: 0;
    }
    .section {
      margin-bottom: 30px;
    }
    .section h2 {
      font-size: 18px;
      color: #374151;
      margin-bottom: 15px;
    }
    .image-container {
      text-align: center;
      margin: 20px 0;
    }
    .image-container img {
      max-width: 100%;
      max-height: 400px;
      border: 1px solid #E5E7EB;
      border-radius: 8px;
    }
    .disclaimer {
      background: #FEF3C7;
      border: 1px solid #F59E0B;
      border-radius: 8px;
      padding: 15px;
      margin-top: 40px;
    }
    .disclaimer h3 {
      color: #92400E;
      margin: 0 0 10px 0;
      font-size: 14px;
    }
    .disclaimer p {
      color: #92400E;
      margin: 0;
      font-size: 12px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #E5E7EB;
      color: #9CA3AF;
      font-size: 12px;
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>MedVis3D - Medical Image Analysis</h1>
    <p>Generated: ${data.date}</p>
  </div>

  <div class="section">
    <h2>Original Image</h2>
    <div class="image-container">
      <img src="${data.originalImageUrl}" alt="Original medical image" />
    </div>
  </div>

  ${data.depthMapUrl ? `
  <div class="section">
    <h2>Depth Analysis</h2>
    <div class="image-container">
      <img src="${data.depthMapUrl}" alt="Depth map visualization" />
    </div>
  </div>
  ` : ''}

  ${data.viewer3DUrl ? `
  <div class="section">
    <h2>3D Visualization</h2>
    <div class="image-container">
      <img src="${data.viewer3DUrl}" alt="3D visualization" />
    </div>
  </div>
  ` : ''}

  ${data.notes ? `
  <div class="section">
    <h2>Notes</h2>
    <p>${data.notes}</p>
  </div>
  ` : ''}

  <div class="disclaimer">
    <h3>⚠️ Important Disclaimer</h3>
    <p>${data.disclaimer}</p>
  </div>

  <div class="footer">
    <p>Generated by MedVis3D - For Educational Purposes Only</p>
    <p>This document is not intended for diagnostic use.</p>
  </div>
</body>
</html>
  `;

  // Create blob from HTML
  const blob = new Blob([html], { type: 'text/html' });
  return blob;
}

export function downloadReport(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printReport(blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, '_blank');
  if (printWindow) {
    printWindow.onload = () => {
      printWindow.print();
    };
  }
  // Clean up after a delay
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}
